version: '3.1'

services:

  db:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data
      - $PWD/backups:/backups

volumes:
  pgdata: